### ISSUE TITLE
give a reference for the first repo 

### ISSUE THREAD

**Issue by omurugur** [security-cheatsheet/cmd-command-cheat-sheet#1]
Hi @ismailtasdelen

There is a copy here. Please give a reference loan for the first repo.

https://officeteam.tech/downloads/lista-de-comandos-cmd.txt

**Comment by ismailtasdelen** [comment]
Hi @omurugur,

Of course I will do this. Because I'm not you You weren't as ethical as I was.I know people like that. I pull the pin. And I am waiting for a response. He tells me who he is. This is really a fair method.

Thanks issue @omurugur
